export const ca = {
  states: {
    disconnected: "Sense vehicle",
    unavailable: "No disponible",
    charging: "Carregant",
    complete: "Càrrega completa",
    timer: "Càrrega programada",
    updating: "Actualitzant",
    control_pilot: "Error Control Pilot",
    load_balancing: "Error Load Balancing",
    error: "Error del carregador",
    waiting_power: "Vehicle connectat",
    wifi_connected: "Wi-Fi connectat",
    wifi_connecting: "Connectant Wi-Fi",
  },
  details: {
    disconnected: "Trydan preparat",
    unavailable: "Revisa la entitat principal",
    charging: "Energia cap al vehicle",
    complete: "Ja pots desconnectar el vehicle",
    timer: "El temporitzador és actiu",
    updating: "No desconnectis el carregador",
    control_pilot: "Revisa la comunicació amb el vehicle",
    load_balancing: "Revisa el balanceig local",
    error: "Revisa el diagnòstic",
    waiting_power: "Esperant inici o potència",
    wifi_connected: "Connexió restablerta",
    wifi_connecting: "Intentant connectar",
  },
  badges: {
    paused: "Pausada",
    locked: "Blocat",
    timer: "Temporitzador",
    waiting_power: "Esperant potència",
  },
  labels: {
    brand: "V2C · TRYDAN",
    now: "ara",
    session: "Sessió",
    power: "Potència",
    energy: "Energia",
    time: "Temps",
    intensity: "Intensitat de càrrega",
    advanced: "Ajustos Trydan",
    chargingControls: "Càrrega",
    energyControls: "Energia dinàmica",
    lightControls: "Il·luminació",
    unavailableEntity: "Entitat no disponible",
    actionPending: "Aplicant el canvi",
    actionDone: "Canvi confirmat",
    actionFailed: "No s'ha pogut aplicar el canvi",
    additionalStatus: "Estat addicional",
    energyFlow: "Flux energètic",
    voltage: "Voltatge",
    diagnostics: "Diagnòstic",
    configuration: "Configuració",
  },
  actions: {
    pause: "Pausa",
    resume: "Reprèn",
    lock: "Bloca l'EVSE",
    unlock: "Desbloca l'EVSE",
    timer: "Temporitzador",
    dynamic: "Modulació dinàmica",
    pauseDynamic: "Pausa el control dinàmic",
    logoLed: "LED del logo",
    lightLed: "Llum del carregador",
    chargeMode: "Mode de càrrega",
    confirmLock: "Vols blocar el carregador V2C?",
  },
  flows: {
    solar: "Solar",
    grid: "Xarxa",
    home: "Casa",
    battery: "Bateria",
    charger: "Cotxe",
    import: "Importa",
    export: "Exporta",
    charge: "Carrega",
    discharge: "Descarrega",
    consume: "Consumeix",
    produce: "Produeix",
    idle: "En repòs",
    unknown: "Sense dades",
    activeFlow: "Flux energètic actiu",
    noFlow: "Sense flux energètic",
    partialData: "Dades energètiques parcials",
    noData: "Sense dades energètiques",
  },
  editor: {
    title: "V2C Trydan Card",
    entity: "Entitat V2C principal",
    name: "Nom",
    location: "Ubicació",
    statusEntity: "Estat visual opcional",
    gridPower: "Potència de xarxa",
    solarPower: "Potència solar",
    batteryPower: "Potència de bateria",
    voltage: "Voltatge",
    language: "Idioma",
    theme: "Tema",
    displayMode: "Mida de la targeta",
    themeAuto: "Sistema / Home Assistant",
    themeLight: "Clar",
    themeDark: "Fosc",
    modeStandard: "Estàndard",
    modeCompact: "Compacte",
    modeUltra: "Ultracompacte",
    showEnergyFlow: "Flux d'energia",
    showControls: "Controls de càrrega",
    showAdvanced: "Controls avançats",
    showCharger: "Il·lustració Trydan",
  },
  lcd: {
    // "Esperant EV" is what the hardware itself prints in Catalan, so the replica says
    // the same thing as the charger on the wall. Every string here has to survive
    // foldForLcd and fit twelve cells.
    disconnected: "Esperant EV",
    unavailable: "Sense dades",
    charging: "Carregant",
    complete: "Completa",
    timer: "Programada",
    updating: "Actualitza",
    control_pilot: "Error",
    load_balancing: "Error",
    error: "Error",
    waiting_power: "Connectat",
    wifi_connected: "Wifi OK",
    wifi_connecting: "Connectant",
  },
} as const;
