import type { Dictionary } from './index';

export const da = {
    "states":  {
                   "disconnected":  "Intet køretøj",
                   "unavailable":  "Ikke tilgængelig",
                   "charging":  "Oplader",
                   "complete":  "Opladning fuldført",
                   "timer":  "Planlagt opladning",
                   "updating":  "Opdaterer",
                   "control_pilot":  "Control Pilot-fejl",
                   "load_balancing":  "Belastningsbalanceringsfejl",
                   "error":  "Opladerfejl",
                   "waiting_power":  "Køretøj tilsluttet",
                   "wifi_connected":  "Wi-Fi tilsluttet",
                   "wifi_connecting":  "Tilslutter Wi-Fi"
               },
    "details":  {
                    "disconnected":  "Trydan klar",
                    "unavailable":  "Kontrollér hovedenheden",
                    "charging":  "Energi til køretøjet",
                    "complete":  "Du kan frakoble køretøjet",
                    "timer":  "Timeren er aktiv",
                    "updating":  "Frakobl ikke opladeren",
                    "control_pilot":  "Kontrollér kommunikationen med køretøjet",
                    "load_balancing":  "Kontrollér lokal belastningsbalancering",
                    "error":  "Kontrollér diagnosticeringen",
                    "waiting_power":  "Venter på start eller effekt",
                    "wifi_connected":  "Forbindelse genoprettet",
                    "wifi_connecting":  "Forsøger at oprette forbindelse"
                },
    "badges":  {
                   "paused":  "Sat på pause",
                   "locked":  "Låst",
                   "timer":  "Timer",
                   "waiting_power":  "Venter på effekt"
               },
    "labels":  {
                   "brand":  "V2C · TRYDAN",
                   "now":  "nu",
                   "session":  "Session",
                   "power":  "Effekt",
                   "energy":  "Energi",
                   "time":  "Tid",
                   "intensity":  "Ladestrøm",
                   "advanced":  "Trydan-indstillinger",
                   "chargingControls":  "Opladning",
                   "energyControls":  "Dynamisk energi",
                   "lightControls":  "Belysning",
                   "unavailableEntity":  "Enheden er ikke tilgængelig",
                   "actionPending":  "Anvender ændring",
                   "actionDone":  "Ændring bekræftet",
                   "actionFailed":  "Ændringen kunne ikke anvendes",
                   "additionalStatus":  "Ekstra status",
                   "energyFlow":  "Energiflow",
                   "voltage":  "Spænding",
                   "diagnostics":  "Diagnostik",
                   "configuration":  "Konfiguration"
               },
    "actions":  {
                    "pause":  "Pause",
                    "resume":  "Fortsæt",
                    "lock":  "Lås EVSE",
                    "unlock":  "Lås EVSE op",
                    "timer":  "Timer",
                    "dynamic":  "Dynamisk modulering",
                    "pauseDynamic":  "Sæt dynamisk styring på pause",
                    "logoLed":  "Logo-LED",
                    "lightLed":  "Opladerlys",
                    "chargeMode":  "Opladningstilstand",
                    "confirmLock":  "Lås V2C-opladeren?"
                },
    "flows":  {
                  "solar":  "Sol",
                  "grid":  "Elnet",
                  "home":  "Hjem",
                  "battery":  "Batteri",
                  "charger":  "Bil",
                  "import":  "Import",
                  "export":  "Eksport",
                  "charge":  "Oplader",
                  "discharge":  "Aflader",
                  "consume":  "Forbrug",
                  "produce":  "Produktion",
                  "idle":  "Inaktiv",
                  "unknown":  "Ingen data",
                  "activeFlow":  "Aktivt energiflow",
                  "noFlow":  "Intet energiflow",
                  "partialData":  "Delvise energidata",
                  "noData":  "Ingen energidata"
              },
    "editor":  {
                   "title":  "V2C Trydan Card",
                   "entity":  "Primær V2C-enhed",
                   "name":  "Navn",
                   "location":  "Placering",
                   "statusEntity":  "Optional visual status",
                   "gridPower":  "Grid power",
                   "solarPower":  "Solar power",
                   "batteryPower":  "Battery power",
                   "voltage":  "Voltage",
                   "language":  "Sprog",
                   "theme":  "Tema",
                   "displayMode":  "Kortstørrelse",
                   "themeAuto":  "System / Home Assistant",
                   "themeLight":  "Lys",
                   "themeDark":  "Mørk",
                   "modeStandard":  "Standard",
                   "modeCompact":  "Kompakt",
                   "modeUltra":  "Ultrakompakt",
                   "showEnergyFlow":  "Energiflow",
                   "showControls":  "Opladningskontroller",
                   "showAdvanced":  "Avancerede kontroller",
                   "showCharger":  "Trydan-illustration"
               },
    "lcd":  {
                "disconnected":  "VENTER EV",
                "unavailable":  "Offline",
                "charging":  "EV OPLADNING",
                "complete":  "Færdig",
                "timer":  "Timer",
                "updating":  "Opdaterer",
                "control_pilot":  "Fejl",
                "load_balancing":  "Fejl",
                "error":  "Fejl",
                "waiting_power":  "EV TILSLUTTET",
                "wifi_connected":  "Wifi OK",
                "wifi_connecting":  "Tilslutter"
            }
} satisfies Dictionary;
