import type { Dictionary } from './index';

export const de = {
    "states":  {
                   "disconnected":  "Kein Fahrzeug",
                   "unavailable":  "Nicht verfügbar",
                   "charging":  "Laden",
                   "complete":  "Ladevorgang abgeschlossen",
                   "timer":  "Geplantes Laden",
                   "updating":  "Aktualisierung",
                   "control_pilot":  "Control-Pilot-Fehler",
                   "load_balancing":  "Lastverteilungsfehler",
                   "error":  "Ladegerätfehler",
                   "waiting_power":  "Fahrzeug verbunden",
                   "wifi_connected":  "WLAN verbunden",
                   "wifi_connecting":  "WLAN wird verbunden"
               },
    "details":  {
                    "disconnected":  "Trydan bereit",
                    "unavailable":  "Hauptentität prüfen",
                    "charging":  "Energie fließt zum Fahrzeug",
                    "complete":  "Fahrzeug kann getrennt werden",
                    "timer":  "Timer ist aktiv",
                    "updating":  "Ladegerät nicht trennen",
                    "control_pilot":  "Fahrzeugkommunikation prüfen",
                    "load_balancing":  "Lokale Lastverteilung prüfen",
                    "error":  "Diagnose prüfen",
                    "waiting_power":  "Warten auf Start oder Leistung",
                    "wifi_connected":  "Verbindung wiederhergestellt",
                    "wifi_connecting":  "Verbindungsversuch läuft"
                },
    "badges":  {
                   "paused":  "Pausiert",
                   "locked":  "Gesperrt",
                   "timer":  "Timer",
                   "waiting_power":  "Wartet auf Leistung"
               },
    "labels":  {
                   "brand":  "V2C · TRYDAN",
                   "now":  "jetzt",
                   "session":  "Sitzung",
                   "power":  "Leistung",
                   "energy":  "Energie",
                   "time":  "Zeit",
                   "intensity":  "Ladestrom",
                   "advanced":  "Trydan-Einstellungen",
                   "chargingControls":  "Laden",
                   "energyControls":  "Dynamische Energie",
                   "lightControls":  "Beleuchtung",
                   "unavailableEntity":  "Entität nicht verfügbar",
                   "actionPending":  "Änderung wird angewendet",
                   "actionDone":  "Änderung bestätigt",
                   "actionFailed":  "Änderung konnte nicht angewendet werden",
                   "additionalStatus":  "Zusätzlicher Status",
                   "energyFlow":  "Energiefluss",
                   "voltage":  "Spannung",
                   "diagnostics":  "Diagnose",
                   "configuration":  "Konfiguration"
               },
    "actions":  {
                    "pause":  "Pausieren",
                    "resume":  "Fortsetzen",
                    "lock":  "EVSE sperren",
                    "unlock":  "EVSE entsperren",
                    "timer":  "Timer",
                    "dynamic":  "Dynamische Regelung",
                    "pauseDynamic":  "Dynamische Regelung pausieren",
                    "logoLed":  "Logo-LED",
                    "lightLed":  "Ladegerätlicht",
                    "chargeMode":  "Lademodus",
                    "confirmLock":  "V2C-Ladegerät sperren?"
                },
    "flows":  {
                  "solar":  "Solar",
                  "grid":  "Netz",
                  "home":  "Haus",
                  "battery":  "Batterie",
                  "charger":  "Auto",
                  "import":  "Bezug",
                  "export":  "Einspeisung",
                  "charge":  "Lädt",
                  "discharge":  "Entlädt",
                  "consume":  "Verbrauch",
                  "produce":  "Erzeugung",
                  "idle":  "Leerlauf",
                  "unknown":  "Keine Daten",
                  "activeFlow":  "Aktiver Energiefluss",
                  "noFlow":  "Kein Energiefluss",
                  "partialData":  "Teilweise Energiedaten",
                  "noData":  "Keine Energiedaten"
              },
    "editor":  {
                   "title":  "V2C Trydan Card",
                   "entity":  "Haupt-V2C-Entität",
                   "name":  "Name",
                   "location":  "Standort",
                   "statusEntity":  "Optional visual status",
                   "gridPower":  "Grid power",
                   "solarPower":  "Solar power",
                   "batteryPower":  "Battery power",
                   "voltage":  "Voltage",
                   "language":  "Sprache",
                   "theme":  "Design",
                   "displayMode":  "Kartengröße",
                   "themeAuto":  "System / Home Assistant",
                   "themeLight":  "Hell",
                   "themeDark":  "Dunkel",
                   "modeStandard":  "Standard",
                   "modeCompact":  "Kompakt",
                   "modeUltra":  "Ultrakompakt",
                   "showEnergyFlow":  "Energiefluss",
                   "showControls":  "Ladesteuerung",
                   "showAdvanced":  "Erweiterte Steuerung",
                   "showCharger":  "Trydan-Abbildung"
               },
    "lcd":  {
                "disconnected":  "Kein EV",
                "unavailable":  "Offline",
                "charging":  "Laden",
                "complete":  "Fertig",
                "timer":  "Timer",
                "updating":  "Update",
                "control_pilot":  "Fehler",
                "load_balancing":  "Fehler",
                "error":  "Fehler",
                "waiting_power":  "Verbunden",
                "wifi_connected":  "WLAN OK",
                "wifi_connecting":  "Verbinden"
            }
} satisfies Dictionary;
