export const en = {
  states: {
    disconnected: "No vehicle",
    unavailable: "Unavailable",
    charging: "Charging",
    complete: "Charge complete",
    timer: "Scheduled charge",
    updating: "Updating",
    control_pilot: "Control Pilot error",
    load_balancing: "Load Balancing error",
    error: "Charger error",
    waiting_power: "Vehicle connected",
    wifi_connected: "Wi-Fi connected",
    wifi_connecting: "Connecting Wi-Fi",
  },
  details: {
    disconnected: "Trydan ready",
    unavailable: "Check the main entity",
    charging: "Energy flowing to the vehicle",
    complete: "You can disconnect the vehicle",
    timer: "The timer is active",
    updating: "Do not disconnect the charger",
    control_pilot: "Check vehicle communication",
    load_balancing: "Check local load balancing",
    error: "Review diagnostics",
    waiting_power: "Waiting to start or for power",
    wifi_connected: "Connection restored",
    wifi_connecting: "Trying to connect",
  },
  badges: {
    paused: "Paused",
    locked: "Locked",
    timer: "Timer",
    waiting_power: "Waiting for power",
  },
  labels: {
    brand: "V2C · TRYDAN",
    now: "now",
    session: "Session",
    power: "Power",
    energy: "Energy",
    time: "Time",
    intensity: "Charging current",
    advanced: "Trydan settings",
    chargingControls: "Charging",
    energyControls: "Dynamic energy",
    lightControls: "Lighting",
    unavailableEntity: "Entity unavailable",
    actionPending: "Applying change",
    actionDone: "Change confirmed",
    actionFailed: "Could not apply change",
    additionalStatus: "Additional status",
    energyFlow: "Energy flow",
    voltage: "Voltage",
    diagnostics: "Diagnostics",
    configuration: "Configuration",
  },
  actions: {
    pause: "Pause",
    resume: "Resume",
    lock: "Lock EVSE",
    unlock: "Unlock EVSE",
    timer: "Timer",
    dynamic: "Dynamic modulation",
    pauseDynamic: "Pause dynamic control",
    logoLed: "Logo LED",
    lightLed: "Charger light",
    chargeMode: "Charge mode",
    confirmLock: "Lock the V2C charger?",
  },
  flows: {
    solar: "Solar",
    grid: "Grid",
    home: "Home",
    battery: "Battery",
    charger: "Car",
    import: "Importing",
    export: "Exporting",
    charge: "Charging",
    discharge: "Discharging",
    consume: "Consuming",
    produce: "Producing",
    idle: "Idle",
    unknown: "No data",
    activeFlow: "Energy flowing",
    noFlow: "No energy flow",
    partialData: "Partial energy data",
    noData: "No energy data",
  },
  editor: {
    title: "V2C Trydan Card",
    entity: "Main V2C entity",
    name: "Name",
    location: "Location",
    statusEntity: "Optional visual status",
    gridPower: "Grid power",
    solarPower: "Solar power",
    batteryPower: "Battery power",
    voltage: "Voltage",
    language: "Language",
    theme: "Theme",
    displayMode: "Card size",
    themeAuto: "System / Home Assistant",
    themeLight: "Light",
    themeDark: "Dark",
    modeStandard: "Standard",
    modeCompact: "Compact",
    modeUltra: "Ultra compact",
    showEnergyFlow: "Energy flow",
    showControls: "Charging controls",
    showAdvanced: "Advanced controls",
    showCharger: "Trydan artwork",
  },
  /**
   * Short, device-shaped status words for the LCD replica (see lcd-copy.ts) - not the same
   * copy as `states`/`details` above, which are full sentences for the accessible status
   * text next to the artwork. control_pilot/load_balancing share the same word as error:
   * the real screen has no room to spell out which fault this is, only a generic word and a
   * numeric code.
   */
  lcd: {
    disconnected: "No EV",
    unavailable: "Offline",
    charging: "Charging",
    complete: "Done",
    timer: "Timer",
    updating: "Updating",
    control_pilot: "Error",
    load_balancing: "Error",
    error: "Error",
    waiting_power: "Ready",
    wifi_connected: "Wifi OK",
    wifi_connecting: "Wifi...",
  },
} as const;
