export const es = {
  states: {
    disconnected: "Sin vehículo",
    unavailable: "No disponible",
    charging: "Cargando",
    complete: "Carga completa",
    timer: "Carga programada",
    updating: "Actualizando",
    control_pilot: "Error Control Pilot",
    load_balancing: "Error Load Balancing",
    error: "Error del cargador",
    waiting_power: "Vehículo conectado",
    wifi_connected: "Wi-Fi conectado",
    wifi_connecting: "Conectando Wi-Fi",
  },
  details: {
    disconnected: "Trydan preparado",
    unavailable: "Revisa la entidad principal",
    charging: "Energía hacia el vehículo",
    complete: "Puedes desconectar el vehículo",
    timer: "El temporizador está activo",
    updating: "No desconectes el cargador",
    control_pilot: "Revisa la comunicación con el vehículo",
    load_balancing: "Revisa el balanceo local",
    error: "Revisa el diagnóstico",
    waiting_power: "Esperando inicio o potencia",
    wifi_connected: "Conexión restablecida",
    wifi_connecting: "Intentando conectar",
  },
  badges: {
    paused: "Pausada",
    locked: "Bloqueado",
    timer: "Temporizador",
    waiting_power: "Esperando potencia",
  },
  labels: {
    brand: "V2C · TRYDAN",
    now: "ahora",
    session: "Sesión",
    power: "Potencia",
    energy: "Energía",
    time: "Tiempo",
    intensity: "Intensidad de carga",
    advanced: "Ajustes Trydan",
    chargingControls: "Carga",
    energyControls: "Energía dinámica",
    lightControls: "Iluminación",
    unavailableEntity: "Entidad no disponible",
    actionPending: "Aplicando cambio",
    actionDone: "Cambio confirmado",
    actionFailed: "No se pudo aplicar el cambio",
    additionalStatus: "Estado adicional",
    energyFlow: "Flujo energético",
    voltage: "Voltaje",
    diagnostics: "Diagnóstico",
    configuration: "Configuración",
  },
  actions: {
    pause: "Pausar",
    resume: "Reanudar",
    lock: "Bloquear EVSE",
    unlock: "Desbloquear EVSE",
    timer: "Temporizador",
    dynamic: "Modulación dinámica",
    pauseDynamic: "Pausar control dinámico",
    logoLed: "Logo LED",
    lightLed: "Luz del cargador",
    chargeMode: "Modo de carga",
    confirmLock: "¿Bloquear el cargador V2C?",
  },
  flows: {
    solar: "Solar",
    grid: "Red",
    home: "Casa",
    battery: "Batería",
    charger: "Coche",
    import: "Importa",
    export: "Exporta",
    charge: "Carga",
    discharge: "Descarga",
    consume: "Consume",
    produce: "Produce",
    idle: "En reposo",
    unknown: "Sin datos",
    activeFlow: "Flujo energético activo",
    noFlow: "Sin flujo energético",
    partialData: "Datos energéticos parciales",
    noData: "Sin datos energéticos",
  },
  editor: {
    title: "V2C Trydan Card",
    entity: "Entidad V2C principal",
    name: "Nombre",
    location: "Ubicación",
    statusEntity: "Estado visual opcional",
    gridPower: "Potencia de red",
    solarPower: "Potencia solar",
    batteryPower: "Potencia de batería",
    voltage: "Voltaje",
    language: "Idioma",
    theme: "Tema",
    displayMode: "Tamaño de tarjeta",
    themeAuto: "Sistema / Home Assistant",
    themeLight: "Claro",
    themeDark: "Oscuro",
    modeStandard: "Estándar",
    modeCompact: "Compacto",
    modeUltra: "Ultracompacto",
    showEnergyFlow: "Flujo de energía",
    showControls: "Controles de carga",
    showAdvanced: "Controles avanzados",
    showCharger: "Ilustración Trydan",
  },
  lcd: {
    disconnected: "Sin EV",
    unavailable: "Sin datos",
    charging: "Cargando",
    complete: "Completa",
    timer: "Programa",
    updating: "Actualiza",
    control_pilot: "Error",
    load_balancing: "Error",
    error: "Error",
    waiting_power: "Conectado",
    wifi_connected: "Wifi OK",
    wifi_connecting: "Conectando",
  },
} as const;
