import type { Dictionary } from './index';

export const fr = {
    "states":  {
                   "disconnected":  "Aucun véhicule",
                   "unavailable":  "Indisponible",
                   "charging":  "En charge",
                   "complete":  "Charge terminée",
                   "timer":  "Charge programmée",
                   "updating":  "Mise à jour",
                   "control_pilot":  "Erreur Control Pilot",
                   "load_balancing":  "Erreur d\u0027équilibrage de charge",
                   "error":  "Erreur du chargeur",
                   "waiting_power":  "Véhicule connecté",
                   "wifi_connected":  "Wi-Fi connecté",
                   "wifi_connecting":  "Connexion Wi-Fi"
               },
    "details":  {
                    "disconnected":  "Trydan prêt",
                    "unavailable":  "Vérifiez l\u0027entité principale",
                    "charging":  "Énergie vers le véhicule",
                    "complete":  "Vous pouvez débrancher le véhicule",
                    "timer":  "Le minuteur est actif",
                    "updating":  "Ne débranchez pas le chargeur",
                    "control_pilot":  "Vérifiez la communication avec le véhicule",
                    "load_balancing":  "Vérifiez l\u0027équilibrage local",
                    "error":  "Vérifiez le diagnostic",
                    "waiting_power":  "En attente du démarrage ou de puissance",
                    "wifi_connected":  "Connexion rétablie",
                    "wifi_connecting":  "Tentative de connexion"
                },
    "badges":  {
                   "paused":  "En pause",
                   "locked":  "Verrouillé",
                   "timer":  "Minuteur",
                   "waiting_power":  "En attente de puissance"
               },
    "labels":  {
                   "brand":  "V2C · TRYDAN",
                   "now":  "maintenant",
                   "session":  "Session",
                   "power":  "Puissance",
                   "energy":  "Énergie",
                   "time":  "Temps",
                   "intensity":  "Courant de charge",
                   "advanced":  "Réglages Trydan",
                   "chargingControls":  "Charge",
                   "energyControls":  "Énergie dynamique",
                   "lightControls":  "Éclairage",
                   "unavailableEntity":  "Entité indisponible",
                   "actionPending":  "Modification en cours",
                   "actionDone":  "Modification confirmée",
                   "actionFailed":  "Impossible d\u0027appliquer la modification",
                   "additionalStatus":  "État supplémentaire",
                   "energyFlow":  "Flux d\u0027énergie",
                   "voltage":  "Tension",
                   "diagnostics":  "Diagnostic",
                   "configuration":  "Configuration"
               },
    "actions":  {
                    "pause":  "Mettre en pause",
                    "resume":  "Reprendre",
                    "lock":  "Verrouiller l\u0027EVSE",
                    "unlock":  "Déverrouiller l\u0027EVSE",
                    "timer":  "Minuteur",
                    "dynamic":  "Modulation dynamique",
                    "pauseDynamic":  "Suspendre le contrôle dynamique",
                    "logoLed":  "LED du logo",
                    "lightLed":  "Éclairage du chargeur",
                    "chargeMode":  "Mode de charge",
                    "confirmLock":  "Verrouiller le chargeur V2C ?"
                },
    "flows":  {
                  "solar":  "Solaire",
                  "grid":  "Réseau",
                  "home":  "Maison",
                  "battery":  "Batterie",
                  "charger":  "Voiture",
                  "import":  "Importation",
                  "export":  "Exportation",
                  "charge":  "Charge",
                  "discharge":  "Décharge",
                  "consume":  "Consommation",
                  "produce":  "Production",
                  "idle":  "Au repos",
                  "unknown":  "Aucune donnée",
                  "activeFlow":  "Flux d\u0027énergie actif",
                  "noFlow":  "Aucun flux d\u0027énergie",
                  "partialData":  "Données énergétiques partielles",
                  "noData":  "Aucune donnée énergétique"
              },
    "editor":  {
                   "title":  "V2C Trydan Card",
                   "entity":  "Entité V2C principale",
                   "name":  "Nom",
                   "location":  "Emplacement",
                   "statusEntity":  "Optional visual status",
                   "gridPower":  "Grid power",
                   "solarPower":  "Solar power",
                   "batteryPower":  "Battery power",
                   "voltage":  "Voltage",
                   "language":  "Langue",
                   "theme":  "Thème",
                   "displayMode":  "Taille de la carte",
                   "themeAuto":  "Système / Home Assistant",
                   "themeLight":  "Clair",
                   "themeDark":  "Sombre",
                   "modeStandard":  "Standard",
                   "modeCompact":  "Compact",
                   "modeUltra":  "Ultra compact",
                   "showEnergyFlow":  "Flux d\u0027énergie",
                   "showControls":  "Commandes de charge",
                   "showAdvanced":  "Commandes avancées",
                   "showCharger":  "Illustration Trydan"
               },
    "lcd":  {
                "disconnected":  "EN ATTENTE VE",
                "unavailable":  "Indispo",
                "charging":  "RECHARGER VE",
                "complete":  "Terminée",
                "timer":  "Minuteur",
                "updating":  "MAJ",
                "control_pilot":  "Erreur",
                "load_balancing":  "Erreur",
                "error":  "Erreur",
                "waiting_power":  "VE CONNECTE",
                "wifi_connected":  "Wifi OK",
                "wifi_connecting":  "Connexion"
            }
} satisfies Dictionary;
