import type { Dictionary } from './index';

export const it = {
    "states":  {
                   "disconnected":  "Nessun veicolo",
                   "unavailable":  "Non disponibile",
                   "charging":  "In carica",
                   "complete":  "Ricarica completata",
                   "timer":  "Ricarica programmata",
                   "updating":  "Aggiornamento",
                   "control_pilot":  "Errore Control Pilot",
                   "load_balancing":  "Errore Load Balancing",
                   "error":  "Errore del caricatore",
                   "waiting_power":  "Veicolo collegato",
                   "wifi_connected":  "Wi-Fi connesso",
                   "wifi_connecting":  "Connessione Wi-Fi"
               },
    "details":  {
                    "disconnected":  "Trydan pronto",
                    "unavailable":  "Controlla l\u0027entità principale",
                    "charging":  "Energia verso il veicolo",
                    "complete":  "Puoi scollegare il veicolo",
                    "timer":  "Il timer è attivo",
                    "updating":  "Non scollegare il caricatore",
                    "control_pilot":  "Controlla la comunicazione con il veicolo",
                    "load_balancing":  "Controlla il bilanciamento locale",
                    "error":  "Controlla la diagnostica",
                    "waiting_power":  "In attesa dell\u0027avvio o della potenza",
                    "wifi_connected":  "Connessione ripristinata",
                    "wifi_connecting":  "Tentativo di connessione"
                },
    "badges":  {
                   "paused":  "In pausa",
                   "locked":  "Bloccato",
                   "timer":  "Timer",
                   "waiting_power":  "In attesa di potenza"
               },
    "labels":  {
                   "brand":  "V2C · TRYDAN",
                   "now":  "ora",
                   "session":  "Sessione",
                   "power":  "Potenza",
                   "energy":  "Energia",
                   "time":  "Tempo",
                   "intensity":  "Corrente di ricarica",
                   "advanced":  "Impostazioni Trydan",
                   "chargingControls":  "Ricarica",
                   "energyControls":  "Energia dinamica",
                   "lightControls":  "Illuminazione",
                   "unavailableEntity":  "Entità non disponibile",
                   "actionPending":  "Modifica in corso",
                   "actionDone":  "Modifica confermata",
                   "actionFailed":  "Impossibile applicare la modifica",
                   "additionalStatus":  "Stato aggiuntivo",
                   "energyFlow":  "Flusso energetico",
                   "voltage":  "Tensione",
                   "diagnostics":  "Diagnostica",
                   "configuration":  "Configurazione"
               },
    "actions":  {
                    "pause":  "Pausa",
                    "resume":  "Riprendi",
                    "lock":  "Blocca EVSE",
                    "unlock":  "Sblocca EVSE",
                    "timer":  "Timer",
                    "dynamic":  "Modulazione dinamica",
                    "pauseDynamic":  "Pausa controllo dinamico",
                    "logoLed":  "LED logo",
                    "lightLed":  "Luce caricatore",
                    "chargeMode":  "Modalità di ricarica",
                    "confirmLock":  "Bloccare il caricatore V2C?"
                },
    "flows":  {
                  "solar":  "Solare",
                  "grid":  "Rete",
                  "home":  "Casa",
                  "battery":  "Batteria",
                  "charger":  "Auto",
                  "import":  "Importazione",
                  "export":  "Esportazione",
                  "charge":  "Ricarica",
                  "discharge":  "Scarica",
                  "consume":  "Consumo",
                  "produce":  "Produzione",
                  "idle":  "Inattivo",
                  "unknown":  "Nessun dato",
                  "activeFlow":  "Flusso energetico attivo",
                  "noFlow":  "Nessun flusso energetico",
                  "partialData":  "Dati energetici parziali",
                  "noData":  "Nessun dato energetico"
              },
    "editor":  {
                   "title":  "V2C Trydan Card",
                   "entity":  "Entità V2C principale",
                   "name":  "Nome",
                   "location":  "Posizione",
                   "statusEntity":  "Optional visual status",
                   "gridPower":  "Grid power",
                   "solarPower":  "Solar power",
                   "batteryPower":  "Battery power",
                   "voltage":  "Voltage",
                   "language":  "Lingua",
                   "theme":  "Tema",
                   "displayMode":  "Dimensione scheda",
                   "themeAuto":  "Sistema / Home Assistant",
                   "themeLight":  "Chiaro",
                   "themeDark":  "Scuro",
                   "modeStandard":  "Standard",
                   "modeCompact":  "Compatto",
                   "modeUltra":  "Ultra compatto",
                   "showEnergyFlow":  "Flusso di energia",
                   "showControls":  "Controlli di ricarica",
                   "showAdvanced":  "Controlli avanzati",
                   "showCharger":  "Illustrazione Trydan"
               },
    "lcd":  {
                "disconnected":  "IN ATTESA DI EV",
                "unavailable":  "Non disp",
                "charging":  "RICARICA EV",
                "complete":  "Completa",
                "timer":  "Programma",
                "updating":  "Aggiorna",
                "control_pilot":  "Errore",
                "load_balancing":  "Errore",
                "error":  "Errore",
                "waiting_power":  "VE CONNESSO",
                "wifi_connected":  "Wifi OK",
                "wifi_connecting":  "Connessione"
            }
} satisfies Dictionary;
