import type { Dictionary } from './index';

export const nl = {
    "states":  {
                   "disconnected":  "Geen voertuig",
                   "unavailable":  "Niet beschikbaar",
                   "charging":  "Bezig met laden",
                   "complete":  "Laden voltooid",
                   "timer":  "Gepland laden",
                   "updating":  "Bijwerken",
                   "control_pilot":  "Control Pilot-fout",
                   "load_balancing":  "Load Balancing-fout",
                   "error":  "Laderfout",
                   "waiting_power":  "Voertuig verbonden",
                   "wifi_connected":  "Wi-Fi verbonden",
                   "wifi_connecting":  "Wi-Fi verbinden"
               },
    "details":  {
                    "disconnected":  "Trydan gereed",
                    "unavailable":  "Controleer de hoofdentiteit",
                    "charging":  "Energie naar het voertuig",
                    "complete":  "Je kunt het voertuig loskoppelen",
                    "timer":  "De timer is actief",
                    "updating":  "Koppel de lader niet los",
                    "control_pilot":  "Controleer de voertuigcommunicatie",
                    "load_balancing":  "Controleer lokale load balancing",
                    "error":  "Controleer de diagnose",
                    "waiting_power":  "Wachten op start of vermogen",
                    "wifi_connected":  "Verbinding hersteld",
                    "wifi_connecting":  "Verbinding wordt geprobeerd"
                },
    "badges":  {
                   "paused":  "Gepauzeerd",
                   "locked":  "Vergrendeld",
                   "timer":  "Timer",
                   "waiting_power":  "Wacht op vermogen"
               },
    "labels":  {
                   "brand":  "V2C · TRYDAN",
                   "now":  "nu",
                   "session":  "Sessie",
                   "power":  "Vermogen",
                   "energy":  "Energie",
                   "time":  "Tijd",
                   "intensity":  "Laadstroom",
                   "advanced":  "Trydan-instellingen",
                   "chargingControls":  "Laden",
                   "energyControls":  "Dynamische energie",
                   "lightControls":  "Verlichting",
                   "unavailableEntity":  "Entiteit niet beschikbaar",
                   "actionPending":  "Wijziging toepassen",
                   "actionDone":  "Wijziging bevestigd",
                   "actionFailed":  "Wijziging kon niet worden toegepast",
                   "additionalStatus":  "Aanvullende status",
                   "energyFlow":  "Energiestroom",
                   "voltage":  "Spanning",
                   "diagnostics":  "Diagnostiek",
                   "configuration":  "Configuratie"
               },
    "actions":  {
                    "pause":  "Pauzeren",
                    "resume":  "Hervatten",
                    "lock":  "EVSE vergrendelen",
                    "unlock":  "EVSE ontgrendelen",
                    "timer":  "Timer",
                    "dynamic":  "Dynamische modulatie",
                    "pauseDynamic":  "Dynamische regeling pauzeren",
                    "logoLed":  "Logo-led",
                    "lightLed":  "Laderverlichting",
                    "chargeMode":  "Laadmodus",
                    "confirmLock":  "V2C-lader vergrendelen?"
                },
    "flows":  {
                  "solar":  "Zon",
                  "grid":  "Net",
                  "home":  "Huis",
                  "battery":  "Batterij",
                  "charger":  "Auto",
                  "import":  "Import",
                  "export":  "Export",
                  "charge":  "Laden",
                  "discharge":  "Ontladen",
                  "consume":  "Verbruik",
                  "produce":  "Productie",
                  "idle":  "In rust",
                  "unknown":  "Geen gegevens",
                  "activeFlow":  "Actieve energiestroom",
                  "noFlow":  "Geen energiestroom",
                  "partialData":  "Gedeeltelijke energiegegevens",
                  "noData":  "Geen energiegegevens"
              },
    "editor":  {
                   "title":  "V2C Trydan Card",
                   "entity":  "Hoofd-V2C-entiteit",
                   "name":  "Naam",
                   "location":  "Locatie",
                   "statusEntity":  "Optional visual status",
                   "gridPower":  "Grid power",
                   "solarPower":  "Solar power",
                   "batteryPower":  "Battery power",
                   "voltage":  "Voltage",
                   "language":  "Taal",
                   "theme":  "Thema",
                   "displayMode":  "Kaartgrootte",
                   "themeAuto":  "Systeem / Home Assistant",
                   "themeLight":  "Licht",
                   "themeDark":  "Donker",
                   "modeStandard":  "Standaard",
                   "modeCompact":  "Compact",
                   "modeUltra":  "Ultracompact",
                   "showEnergyFlow":  "Energiestroom",
                   "showControls":  "Laadbediening",
                   "showAdvanced":  "Geavanceerde bediening",
                   "showCharger":  "Trydan-afbeelding"
               },
    "lcd":  {
                "disconnected":  "Geen EV",
                "unavailable":  "Offline",
                "charging":  "Laden",
                "complete":  "Klaar",
                "timer":  "Timer",
                "updating":  "Update",
                "control_pilot":  "Fout",
                "load_balancing":  "Fout",
                "error":  "Fout",
                "waiting_power":  "Verbonden",
                "wifi_connected":  "Wifi OK",
                "wifi_connecting":  "Verbinden"
            }
} satisfies Dictionary;
