import type { Dictionary } from './index';

export const no = {
    "states":  {
                   "disconnected":  "Ingen bil",
                   "unavailable":  "Ikke tilgjengelig",
                   "charging":  "Lader",
                   "complete":  "Lading fullført",
                   "timer":  "Planlagt lading",
                   "updating":  "Oppdaterer",
                   "control_pilot":  "Control Pilot-feil",
                   "load_balancing":  "Lastbalanseringsfeil",
                   "error":  "Laderfeil",
                   "waiting_power":  "Bil tilkoblet",
                   "wifi_connected":  "Wi-Fi tilkoblet",
                   "wifi_connecting":  "Kobler til Wi-Fi"
               },
    "details":  {
                    "disconnected":  "Trydan klar",
                    "unavailable":  "Kontroller hovedenheten",
                    "charging":  "Energi til bilen",
                    "complete":  "Du kan koble fra bilen",
                    "timer":  "Timeren er aktiv",
                    "updating":  "Ikke koble fra laderen",
                    "control_pilot":  "Kontroller kommunikasjonen med bilen",
                    "load_balancing":  "Kontroller lokal lastbalansering",
                    "error":  "Kontroller diagnostikken",
                    "waiting_power":  "Venter på start eller effekt",
                    "wifi_connected":  "Tilkobling gjenopprettet",
                    "wifi_connecting":  "Prøver å koble til"
                },
    "badges":  {
                   "paused":  "Pauset",
                   "locked":  "Låst",
                   "timer":  "Timer",
                   "waiting_power":  "Venter på effekt"
               },
    "labels":  {
                   "brand":  "V2C · TRYDAN",
                   "now":  "nå",
                   "session":  "Økt",
                   "power":  "Effekt",
                   "energy":  "Energi",
                   "time":  "Tid",
                   "intensity":  "Ladestrøm",
                   "advanced":  "Trydan-innstillinger",
                   "chargingControls":  "Lading",
                   "energyControls":  "Dynamisk energi",
                   "lightControls":  "Belysning",
                   "unavailableEntity":  "Enheten er ikke tilgjengelig",
                   "actionPending":  "Bruker endring",
                   "actionDone":  "Endring bekreftet",
                   "actionFailed":  "Kunne ikke bruke endringen",
                   "additionalStatus":  "Ekstra status",
                   "energyFlow":  "Energiflyt",
                   "voltage":  "Spenning",
                   "diagnostics":  "Diagnostikk",
                   "configuration":  "Konfigurasjon"
               },
    "actions":  {
                    "pause":  "Pause",
                    "resume":  "Fortsett",
                    "lock":  "Lås EVSE",
                    "unlock":  "Lås opp EVSE",
                    "timer":  "Timer",
                    "dynamic":  "Dynamisk modulering",
                    "pauseDynamic":  "Sett dynamisk styring på pause",
                    "logoLed":  "Logo-LED",
                    "lightLed":  "Laderlys",
                    "chargeMode":  "Lademodus",
                    "confirmLock":  "Låse V2C-laderen?"
                },
    "flows":  {
                  "solar":  "Sol",
                  "grid":  "Strømnett",
                  "home":  "Hjem",
                  "battery":  "Batteri",
                  "charger":  "Bil",
                  "import":  "Import",
                  "export":  "Eksport",
                  "charge":  "Lader",
                  "discharge":  "Lader ut",
                  "consume":  "Forbruk",
                  "produce":  "Produksjon",
                  "idle":  "Inaktiv",
                  "unknown":  "Ingen data",
                  "activeFlow":  "Aktiv energiflyt",
                  "noFlow":  "Ingen energiflyt",
                  "partialData":  "Delvise energidata",
                  "noData":  "Ingen energidata"
              },
    "editor":  {
                   "title":  "V2C Trydan Card",
                   "entity":  "Primær V2C-enhet",
                   "name":  "Navn",
                   "location":  "Plassering",
                   "statusEntity":  "Optional visual status",
                   "gridPower":  "Grid power",
                   "solarPower":  "Solar power",
                   "batteryPower":  "Battery power",
                   "voltage":  "Voltage",
                   "language":  "Språk",
                   "theme":  "Tema",
                   "displayMode":  "Kortstørrelse",
                   "themeAuto":  "System / Home Assistant",
                   "themeLight":  "Lys",
                   "themeDark":  "Mørk",
                   "modeStandard":  "Standard",
                   "modeCompact":  "Kompakt",
                   "modeUltra":  "Ultrakompakt",
                   "showEnergyFlow":  "Energiflyt",
                   "showControls":  "Ladekontroller",
                   "showAdvanced":  "Avanserte kontroller",
                   "showCharger":  "Trydan-illustrasjon"
               },
    "lcd":  {
                "disconnected":  "Ingen EV",
                "unavailable":  "Offline",
                "charging":  "Lader",
                "complete":  "Ferdig",
                "timer":  "Timer",
                "updating":  "Oppdaterer",
                "control_pilot":  "Feil",
                "load_balancing":  "Feil",
                "error":  "Feil",
                "waiting_power":  "Tilkoblet",
                "wifi_connected":  "Wifi OK",
                "wifi_connecting":  "Kobler til"
            }
} satisfies Dictionary;
