import type { Dictionary } from './index';

export const ro = {
    "states":  {
                   "disconnected":  "Niciun vehicul",
                   "unavailable":  "Indisponibil",
                   "charging":  "Se încarcă",
                   "complete":  "Încărcare finalizată",
                   "timer":  "Încărcare programată",
                   "updating":  "Se actualizează",
                   "control_pilot":  "Eroare Control Pilot",
                   "load_balancing":  "Eroare de echilibrare a sarcinii",
                   "error":  "Eroare încărcător",
                   "waiting_power":  "Vehicul conectat",
                   "wifi_connected":  "Wi-Fi conectat",
                   "wifi_connecting":  "Conectare Wi-Fi"
               },
    "details":  {
                    "disconnected":  "Trydan pregătit",
                    "unavailable":  "Verifică entitatea principală",
                    "charging":  "Energie către vehicul",
                    "complete":  "Poți deconecta vehiculul",
                    "timer":  "Temporizatorul este activ",
                    "updating":  "Nu deconecta încărcătorul",
                    "control_pilot":  "Verifică comunicarea cu vehiculul",
                    "load_balancing":  "Verifică echilibrarea locală",
                    "error":  "Verifică diagnosticul",
                    "waiting_power":  "Se așteaptă pornirea sau puterea",
                    "wifi_connected":  "Conexiune restabilită",
                    "wifi_connecting":  "Se încearcă conectarea"
                },
    "badges":  {
                   "paused":  "În pauză",
                   "locked":  "Blocat",
                   "timer":  "Temporizator",
                   "waiting_power":  "Așteaptă putere"
               },
    "labels":  {
                   "brand":  "V2C · TRYDAN",
                   "now":  "acum",
                   "session":  "Sesiune",
                   "power":  "Putere",
                   "energy":  "Energie",
                   "time":  "Timp",
                   "intensity":  "Curent de încărcare",
                   "advanced":  "Setări Trydan",
                   "chargingControls":  "Încărcare",
                   "energyControls":  "Energie dinamică",
                   "lightControls":  "Iluminare",
                   "unavailableEntity":  "Entitate indisponibilă",
                   "actionPending":  "Se aplică modificarea",
                   "actionDone":  "Modificare confirmată",
                   "actionFailed":  "Modificarea nu a putut fi aplicată",
                   "additionalStatus":  "Stare suplimentară",
                   "energyFlow":  "Flux de energie",
                   "voltage":  "Tensiune",
                   "diagnostics":  "Diagnostic",
                   "configuration":  "Configurare"
               },
    "actions":  {
                    "pause":  "Pauză",
                    "resume":  "Continuă",
                    "lock":  "Blochează EVSE",
                    "unlock":  "Deblochează EVSE",
                    "timer":  "Temporizator",
                    "dynamic":  "Modulare dinamică",
                    "pauseDynamic":  "Întrerupe controlul dinamic",
                    "logoLed":  "LED siglă",
                    "lightLed":  "Lumină încărcător",
                    "chargeMode":  "Mod de încărcare",
                    "confirmLock":  "Blochezi încărcătorul V2C?"
                },
    "flows":  {
                  "solar":  "Solar",
                  "grid":  "Rețea",
                  "home":  "Casă",
                  "battery":  "Baterie",
                  "charger":  "Mașină",
                  "import":  "Import",
                  "export":  "Export",
                  "charge":  "Încărcare",
                  "discharge":  "Descărcare",
                  "consume":  "Consum",
                  "produce":  "Producție",
                  "idle":  "Repaus",
                  "unknown":  "Fără date",
                  "activeFlow":  "Flux de energie activ",
                  "noFlow":  "Fără flux de energie",
                  "partialData":  "Date energetice parțiale",
                  "noData":  "Fără date energetice"
              },
    "editor":  {
                   "title":  "V2C Trydan Card",
                   "entity":  "Entitate V2C principală",
                   "name":  "Nume",
                   "location":  "Locație",
                   "statusEntity":  "Optional visual status",
                   "gridPower":  "Grid power",
                   "solarPower":  "Solar power",
                   "batteryPower":  "Battery power",
                   "voltage":  "Voltage",
                   "language":  "Limbă",
                   "theme":  "Temă",
                   "displayMode":  "Dimensiunea cardului",
                   "themeAuto":  "Sistem / Home Assistant",
                   "themeLight":  "Luminos",
                   "themeDark":  "Întunecat",
                   "modeStandard":  "Standard",
                   "modeCompact":  "Compact",
                   "modeUltra":  "Ultracompact",
                   "showEnergyFlow":  "Flux de energie",
                   "showControls":  "Comenzi de încărcare",
                   "showAdvanced":  "Comenzi avansate",
                   "showCharger":  "Ilustrație Trydan"
               },
    "lcd":  {
                "disconnected":  "Fără EV",
                "unavailable":  "Indisponibil",
                "charging":  "Încarcă",
                "complete":  "Gata",
                "timer":  "Program",
                "updating":  "Actualizează",
                "control_pilot":  "Eroare",
                "load_balancing":  "Eroare",
                "error":  "Eroare",
                "waiting_power":  "Conectat",
                "wifi_connected":  "Wifi OK",
                "wifi_connecting":  "Conectare"
            }
} satisfies Dictionary;
