import type { Dictionary } from './index';

export const sv = {
    "states":  {
                   "disconnected":  "Inget fordon",
                   "unavailable":  "Inte tillgänglig",
                   "charging":  "Laddar",
                   "complete":  "Laddning klar",
                   "timer":  "Schemalagd laddning",
                   "updating":  "Uppdaterar",
                   "control_pilot":  "Control Pilot-fel",
                   "load_balancing":  "Lastbalanseringsfel",
                   "error":  "Laddarfel",
                   "waiting_power":  "Fordon anslutet",
                   "wifi_connected":  "Wi-Fi anslutet",
                   "wifi_connecting":  "Ansluter Wi-Fi"
               },
    "details":  {
                    "disconnected":  "Trydan redo",
                    "unavailable":  "Kontrollera huvudenheten",
                    "charging":  "Energi till fordonet",
                    "complete":  "Du kan koppla från fordonet",
                    "timer":  "Timern är aktiv",
                    "updating":  "Koppla inte från laddaren",
                    "control_pilot":  "Kontrollera fordonskommunikationen",
                    "load_balancing":  "Kontrollera lokal lastbalansering",
                    "error":  "Kontrollera diagnostiken",
                    "waiting_power":  "Väntar på start eller effekt",
                    "wifi_connected":  "Anslutning återställd",
                    "wifi_connecting":  "Försöker ansluta"
                },
    "badges":  {
                   "paused":  "Pausad",
                   "locked":  "Låst",
                   "timer":  "Timer",
                   "waiting_power":  "Väntar på effekt"
               },
    "labels":  {
                   "brand":  "V2C · TRYDAN",
                   "now":  "nu",
                   "session":  "Session",
                   "power":  "Effekt",
                   "energy":  "Energi",
                   "time":  "Tid",
                   "intensity":  "Laddström",
                   "advanced":  "Trydan-inställningar",
                   "chargingControls":  "Laddning",
                   "energyControls":  "Dynamisk energi",
                   "lightControls":  "Belysning",
                   "unavailableEntity":  "Entiteten är inte tillgänglig",
                   "actionPending":  "Tillämpar ändring",
                   "actionDone":  "Ändring bekräftad",
                   "actionFailed":  "Ändringen kunde inte tillämpas",
                   "additionalStatus":  "Ytterligare status",
                   "energyFlow":  "Energiflöde",
                   "voltage":  "Spänning",
                   "diagnostics":  "Diagnostik",
                   "configuration":  "Konfiguration"
               },
    "actions":  {
                    "pause":  "Pausa",
                    "resume":  "Fortsätt",
                    "lock":  "Lås EVSE",
                    "unlock":  "Lås upp EVSE",
                    "timer":  "Timer",
                    "dynamic":  "Dynamisk modulering",
                    "pauseDynamic":  "Pausa dynamisk styrning",
                    "logoLed":  "Logotyp-LED",
                    "lightLed":  "Laddarbelysning",
                    "chargeMode":  "Laddningsläge",
                    "confirmLock":  "Låsa V2C-laddaren?"
                },
    "flows":  {
                  "solar":  "Sol",
                  "grid":  "Elnät",
                  "home":  "Hem",
                  "battery":  "Batteri",
                  "charger":  "Bil",
                  "import":  "Import",
                  "export":  "Export",
                  "charge":  "Laddar",
                  "discharge":  "Urladdning",
                  "consume":  "Förbrukning",
                  "produce":  "Produktion",
                  "idle":  "Viloläge",
                  "unknown":  "Ingen data",
                  "activeFlow":  "Aktivt energiflöde",
                  "noFlow":  "Inget energiflöde",
                  "partialData":  "Delvisa energidata",
                  "noData":  "Inga energidata"
              },
    "editor":  {
                   "title":  "V2C Trydan Card",
                   "entity":  "Primär V2C-entitet",
                   "name":  "Namn",
                   "location":  "Plats",
                   "statusEntity":  "Optional visual status",
                   "gridPower":  "Grid power",
                   "solarPower":  "Solar power",
                   "batteryPower":  "Battery power",
                   "voltage":  "Voltage",
                   "language":  "Språk",
                   "theme":  "Tema",
                   "displayMode":  "Kortstorlek",
                   "themeAuto":  "System / Home Assistant",
                   "themeLight":  "Ljust",
                   "themeDark":  "Mörkt",
                   "modeStandard":  "Standard",
                   "modeCompact":  "Kompakt",
                   "modeUltra":  "Ultrakompakt",
                   "showEnergyFlow":  "Energiflöde",
                   "showControls":  "Laddningskontroller",
                   "showAdvanced":  "Avancerade kontroller",
                   "showCharger":  "Trydan-illustration"
               },
    "lcd":  {
                "disconnected":  "Inget EV",
                "unavailable":  "Offline",
                "charging":  "Laddar",
                "complete":  "Klar",
                "timer":  "Timer",
                "updating":  "Uppdatera",
                "control_pilot":  "Fel",
                "load_balancing":  "Fel",
                "error":  "Fel",
                "waiting_power":  "Anslutet",
                "wifi_connected":  "Wifi OK",
                "wifi_connecting":  "Ansluter"
            }
} satisfies Dictionary;
